kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    k8s-app: prometheus-app-monitor
  name: prometheus-app-monitor
  namespace: ergarcia171-dev
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /q/metrics
      scheme: http
  selector:
    matchLabels:
      app-with-metrics: 'quarkus-app'